name: Deploy Doc

on:
  push:
    branches: [ main ]

env:
  RUST_LOG: info
  CARGO_TERM_COLOR: always
  DOCS_URL: https://os-checker.github.io/docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up author & committer
        run: |
          git config --global user.name "zjp-CN"
          git config --global user.email "jiping_zhou@foxmail.com"
          git config --global committer.name "zjp-CN[bot]"
          git config --global committer.email "zjp-CN[bot]@users.noreply.github.com"

      - name: Update submodules
        run: |
          cargo r -- list-test.json

      - name: Push changes to remote repo
        run: |
          # in case it's outdated in the runner 
          git pull --rebase
          # push to remote repo if any
          git push && true

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: repos/deploy/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
