name: Deploy Doc

on:
  push:
    branches: [ main ]

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build static files
        env:
          CARGO_TERM_COLOR: always
        id: build
        run: |
          cd repos/os-checker-test-suite
          # cargo doc --document-private-items
          cargo doc --document-private-items --workspace --no-deps || true

          cd ../os-checker
          cargo doc --document-private-items --workspace --no-deps || true

          cd ..
          mkdir deploy
          mv os-checker-test-suite/target/doc deploy/os-checker-test-suite
          mv os-checker/target/doc deploy/os-checker
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: repos/deploy/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
